### ISSUE TITLE
delete the particular document

### ISSUE THREAD

**Issue by 00ec454** [googlesamples/android-DirectorySelection#1]
for example given here is the file structure

```
sdCard
 |--MyFolder
     |--File1.txt
```

If i want to delete the `File1.txt`, how do I get the URI of this document?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
