### ISSUE TITLE
build.gradle should not contain a "plus"

### ISSUE THREAD

**Issue by dclaar** [googlesamples/android-DirectorySelection#3]
When trying to build this in Android Studio, get:

Error:Execution failed for task ':Application:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:support-v13:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:recyclerview-v7:26.0.0-alpha1] AndroidManifest.xml:24:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

This is coming from the dependencies: com.android.support:support-v13:25.3.1 and com.android.support:recyclerview-v7:26.0.0-alpha1

The reason this is failing is that the build.gradle for that sample contains a dynamic dependency, i.e. use the latest of one of the support libraries.
This is not recommended, as it makes the build not reproducible

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
