### ISSUE TITLE
How to start at a specific directory?

### ISSUE THREAD

**Issue by Aditya94A** [googlesamples/android-DirectorySelection#4]
When you open the directory picker using the method described, I want it to open at a specific place, not wherever the user left it the last time. The default behavior is inappropriate and unintuitive. I'm not going to ask my users to traverse the entire directory tree over and over to get where they want to go. I can't put this in production.

How to start at a specific directory?

https://stackoverflow.com/questions/30115263/open-specific-directory-using-storage-access-framework

<rant>
This is quite possibly the single worst API I've ever had to deal with, right up there with fragments, content resolver and alarm manager. Why must you make my life harder, Google?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
