### ISSUE TITLE
This is the worst API in all of android

### ISSUE THREAD

**Issue by Aditya94A** [googlesamples/android-DirectorySelection#5]
We are now effectively locked out of the removable SD card unless we're willing to keep prompting the user to pick some directory in the SAF picker.

I have received ~400 1-stars thanks to this. Thank you for the never ending headaches, Google.

**Comment by AndroidDeveloperLB** [comment]
Sadly this seems to becoming worse on Android Q:
https://issuetracker.google.com/issues/128591846
https://issuetracker.google.com/issues/129629193

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
