### ISSUE TITLE
Not supported on Android TV

### ISSUE THREAD

**Issue by burningthumb** [googlesamples/android-DirectorySelection#7]
So after wasting so much time with this rubbish API it turns out its not even supported on Android TV.  Good grief, I think google is being run by 12 year old girls.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
